version: '2'
services:
  db:
    build: ./db
    ports:
     - "3306:3306"
  api:
    build: ./api
    ports:
     - "8080:8080"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./api:/app/api
    